# Generated by Django 5.0.1 on 2024-02-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/shop/products/placeholder.png', upload_to='media/shop/products/'),
        ),
    ]
