# Generated by Django 5.0.1 on 2024-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='shop/products/placeholder.png', upload_to='shop/products'),
        ),
    ]
