# Generated by Django 5.0.2 on 2024-02-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rndapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointoss',
            name='side',
            field=models.CharField(default='tail', max_length=10),
        ),
    ]
